# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaHUqJI6f_08UNZMiDb5QAcKU30MHnLY
"""

!pip install geotile

from geotile import GeoTile

gt=GeoTile('/content/drive/MyDrive/Hetauda_S2_2020_12.tif')
gt.meta

gt.generate_tiles(save_tiles=False)
gt.convert_nan_to_zero()
gt.drop_nan_tiles()
gt.drop_zero_value_tiles()
gt.save_tiles('/content/tiles')

import glob

tiles=glob.glob('/content/tiles/*.tif')
len(tiles)

import numpy as np
import matplotlib.pyplot as plt
from skimage import exposure
import rasterio as rio

img=np.random.randint(len(tiles))
print(img)

src=rio.open(tiles[img])
print(src.meta)

data= src.read()

data=np.transpose(data,(1,2,0))

data_enhanced=np.zeros((256,256,6))
for i in range(data.shape[-1]):
  p2,p98=np.percentile(data[:,:,i],(2,98))
  data_enhanced[:,:,i]=exposure.rescale_intensity(data[:,:,i],in_range=(p2,p98))

fig,(ax1,ax2)=plt.subplots(1,2,figsize=(10,5))
ax1.set_title("RGB image(Original)")
ax2.set_title("RGB image(Enhanced)")
ax1.imshow(data[:,:,0:3])
ax2.imshow(data_enhanced[:,:,0:3])
plt.savefig('output_image.png')
plt.show()